apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app-svc
  namespace: default

spec:
  ports:
  - nodePort: 32425
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: app
  type: NodePort
