apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-2023
  region: eu-central-1
  version: "1.27"

availabilityZones:
  - eu-central-1a
  - eu-central-1b

vpc:
  cidr: "10.0.0.0/16"
